// Canonical backup document types for JoyaControl.
//
// New backups use one public model only: BackupEnvelope. BackupData is an alias
// kept for source compatibility; it is not a second on-disk format. Raw V2-V6
// files are represented internally as LegacyBackupData and are normalized at
// the import boundary before validation or restoration.

export enum BackupDestination {
  LOCAL = 'LOCAL',
  USB = 'USB',
  NETWORK = 'NETWORK',
  SERVER = 'SERVER',
  NAS = 'NAS',
  CLOUD = 'CLOUD',
}

export enum BackupType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
  PRE_RESTORE = 'PRE_RESTORE',
}

export const MIN_SUPPORTED_BACKUP_VERSION = 2;
export const CURRENT_BACKUP_VERSION = 6;

// Single source of truth for exported/restored tables. Tables missing from an
// old backup are deliberately not cleared during restore.
export const BACKUP_TABLE_NAMES = [
  'products',
  'contacts',
  'invoices',
  'invoice_items',
  'purchase_invoices',
  'purchase_invoice_items',
  'expenses',
  'supplier_prices',
  'quotations',
  'quotation_items',
  'layaways',
  'layaway_payments',
  'cash_sessions',
  'company_settings',
  'inventory_adjustments',
  'supplier_invoices',
  'supplier_invoice_payments',
  'users',
  'categories',
  'financial_accounts',
  'financial_movements',
  'invoice_payment_allocations',
  'activity_log',
  'backup_history',
  'system_settings',
] as const;

export type BackupTableName = typeof BACKUP_TABLE_NAMES[number];
export type BackupTables = Partial<Record<BackupTableName, unknown[]>> & Record<string, unknown[] | undefined>;

// Raw files generated by JoyaControl V2-V6 before the canonical envelope.
// Kept only for import compatibility and as the payload inside the envelope.
export interface LegacyBackupData {
  version: number;
  createdAt: string;
  appName: 'JoyaControl';
  tables: BackupTables;
}

export type BackupChecksumScope = 'none' | 'data-v1' | 'document-v1';

export interface BackupMetadata {
  version: number;
  schemaVersion: number;
  databaseVersion: number;
  appVersion: string;
  buildVersion: string;
  createdAt: string;
  createdBy: string;
  deviceId: string;
  recordCount: number;
  backupType: BackupType;
  destination: BackupDestination;
  checksumScope: BackupChecksumScope;
}

// Definitive modern on-disk shape. The top-level compatibility fields mirror
// metadata and are validated for equality, preventing exporter/importer drift.
export interface BackupEnvelope {
  metadata: BackupMetadata;
  checksum: string;
  data: LegacyBackupData;
  version: number;
  databaseVersion: number;
  createdAt: string;
  deviceId: string;
  appVersion: string;
}

// Backward-compatible name: there is only one modern model.
export type BackupData = BackupEnvelope;

export interface BackupHistory {
  id: string;
  date: string;
  type: BackupType | 'restore' | 'restore_failed' | 'validation_failed';
  destination: BackupDestination;
  size: number;
  status: 'success' | 'failed';
  version: number;
  createdBy: string;
  deviceId: string;
  notes?: string;
}

export interface BackupSettings {
  backupEnabled: boolean;
  backupInterval: 'disabled' | '15m' | '1h' | '6h' | '12h' | '24h';
  backupHour: number;
  backupFolder: string;
  maxBackups: number;
  deleteOldBackups: boolean;
  verifyChecksum: boolean;
  backupBeforeRestore: boolean;
  backupOnStartup: boolean;
  backupOnExit: boolean;
  backupOnImport: boolean;
  compressionEnabled: boolean;
  defaultDestination: BackupDestination;
}

export interface BackupValidationResult {
  valid: boolean;
  warnings: string[];
  errors: string[];
  metadata: BackupMetadata | null;
}

export interface BackupInfo {
  date: string;
  sizeKB: number;
  version: number;
  destination: BackupDestination;
  recordCount: number;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asFiniteInteger(value: unknown, fallback = 0): number {
  return typeof value === 'number' && Number.isFinite(value) && Number.isInteger(value)
    ? value
    : fallback;
}

function asString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function isBackupTables(value: unknown): value is BackupTables {
  return isRecord(value);
}

export function isLegacyBackupData(value: unknown): value is LegacyBackupData {
  if (!isRecord(value)) return false;
  return value.appName === 'JoyaControl'
    && isBackupTables(value.tables)
    && typeof value.version === 'number'
    && typeof value.createdAt === 'string';
}

export function countBackupRecords(data: LegacyBackupData): number {
  return Object.values(data.tables).reduce(
    (sum, rows) => sum + (Array.isArray(rows) ? rows.length : 0),
    0,
  );
}

function normalizeMetadata(value: unknown): BackupMetadata {
  const source = isRecord(value) ? value : {};
  const destination = Object.values(BackupDestination).includes(source.destination as BackupDestination)
    ? source.destination as BackupDestination
    : BackupDestination.LOCAL;
  const backupType = Object.values(BackupType).includes(source.backupType as BackupType)
    ? source.backupType as BackupType
    : BackupType.MANUAL;
  const checksumScope: BackupChecksumScope = source.checksumScope === 'document-v1'
    || source.checksumScope === 'data-v1'
    || source.checksumScope === 'none'
    ? source.checksumScope
    : 'data-v1';

  return {
    version: asFiniteInteger(source.version),
    schemaVersion: asFiniteInteger(source.schemaVersion),
    databaseVersion: asFiniteInteger(source.databaseVersion, asFiniteInteger(source.schemaVersion)),
    appVersion: asString(source.appVersion),
    buildVersion: asString(source.buildVersion) || asString(source.appVersion),
    createdAt: asString(source.createdAt),
    createdBy: asString(source.createdBy),
    deviceId: asString(source.deviceId),
    recordCount: asFiniteInteger(source.recordCount, -1),
    backupType,
    destination,
    checksumScope,
  };
}

function wrapLegacyBackup(data: LegacyBackupData): BackupEnvelope {
  const recordCount = countBackupRecords(data);
  const metadata: BackupMetadata = {
    version: data.version,
    schemaVersion: 0,
    databaseVersion: data.version,
    appVersion: 'legacy',
    buildVersion: 'legacy',
    createdAt: data.createdAt,
    createdBy: 'legacy',
    deviceId: 'legacy',
    recordCount,
    backupType: BackupType.MANUAL,
    destination: BackupDestination.LOCAL,
    checksumScope: 'none',
  };

  return {
    metadata,
    checksum: '',
    data,
    version: data.version,
    databaseVersion: data.version,
    createdAt: data.createdAt,
    deviceId: 'legacy',
    appVersion: 'legacy',
  };
}

// Accepts canonical envelopes, the previous {metadata, checksum, data}
// envelope, and raw V2-V6 BackupData files. It never mutates the parsed source.
export function normalizeBackupSource(source: unknown): BackupEnvelope {
  if (isLegacyBackupData(source)) return wrapLegacyBackup(source);
  if (!isRecord(source)) throw new Error('El archivo no contiene un respaldo válido.');

  const payload = source.data;
  if (!isLegacyBackupData(payload)) {
    throw new Error('El archivo no contiene datos de JoyaControl válidos.');
  }

  const metadata = normalizeMetadata(source.metadata);
  const version = asFiniteInteger(source.version, metadata.version || payload.version);
  const databaseVersion = asFiniteInteger(
    source.databaseVersion,
    metadata.databaseVersion || metadata.schemaVersion,
  );
  const createdAt = asString(source.createdAt) || metadata.createdAt;
  const deviceId = asString(source.deviceId) || metadata.deviceId;
  const appVersion = asString(source.appVersion) || metadata.appVersion;

  return {
    metadata,
    checksum: asString(source.checksum),
    data: payload,
    version,
    databaseVersion,
    createdAt,
    deviceId,
    appVersion,
  };
}

// Input protected by checksum in canonical V6 files. The checksum itself is
// excluded, while all metadata and top-level compatibility fields are covered.
export function getBackupChecksumInput(envelope: Omit<BackupEnvelope, 'checksum'> | BackupEnvelope): unknown {
  return {
    metadata: envelope.metadata,
    data: envelope.data,
    version: envelope.version,
    databaseVersion: envelope.databaseVersion,
    createdAt: envelope.createdAt,
    deviceId: envelope.deviceId,
    appVersion: envelope.appVersion,
  };
}
